### ISSUE TITLE
'onKernelController' is strange

### ISSUE THREAD

**Issue by donquixote** [mediamonks/drupal-controller-annotations#8] opened 2017-08-07 13:05 UTC
The ControllerEventSubscriber subscribes to KernelEvents::CONTROLLER with 'onKernelController'.
I don't really understand why this needs to happen.

The way I understand it, the purpose of this module is to create route definitions from annotations.
So the annotations should be read whenever the *.routing.yml is read, which is on every cache rebuild.
There should be no need to read annotations when visiting the page.

So I don't really know what the 'onKernelController' is doing.

**Comment by slootjes** [comment] 2017-08-07 13:24
When a route it hit the listener will check if there are annotations that need to modify the request object (such as Security, Method, Cache). 

It would maybe be possible to run this for every route and update it in cache but since that's not a part of the original bundle that would probably require quite some work. Since the current behavior is as intended I'm closing the ticket. Feel free to re-open it if you have a solution to optimize it.

**Closed as completed by slootjes** 2017-08-07 13:24 UTC

**Comment by slootjes** [comment] 2017-08-09 09:26
I did some digging and the Security and Method annotations are actually stored properly in the dump so this process is optimized as expected. The ControllerEventSubscriber just makes sure the parameters are set to the request so this is doing something different from the routing as this is an important element for ParamConverter and Template annotations.

Since it would be nice to get the exception about using multiple tags during a cache rebuild I will try to see if I can implement this check in the rebuild process too.

**Comment by slootjes** [comment] 2017-08-09 12:33
Just to inform you because you triggered me into looking into performance a little more: I also implemented the cached annotation reader provided by Doctrine with an adapter which uses Drupal default cache backend so loading annotations should be optimized now too :)

**Comment by donquixote** [comment] 2017-08-09 18:57
> The ControllerEventSubscriber just makes sure the parameters are set to the request so this is doing something different from the routing as this is an important element for ParamConverter and Template annotations.

This is strange.
Without annotations, routes in Drupal 8 have all their information stored in the route itself via the *.routing.yml file. There is no need to any additional lookups on page visit. Even param converters (the Drupal param converters, not the Symfony ones) are part of the route definition array from the yml file.
So whatever happens here seems to be in addition to Drupal core routing.

If all we want is to replicate the functionality from the routing.yml files, we don't need onKernelController.

**Comment by donquixote** [comment] 2017-08-09 19:00
E.g. the RouteParameter annotation proposed [here](https://github.com/mediamonks/drupal-controller-annotations/pull/7/commits/944c169a11060c1aedef9b1e5793f762c0b6b015) would give you core param converter without the additional onKernelController event. Well aside of the bug this code contains..

**Comment by slootjes** [comment] 2017-08-09 19:03
The Drupal param converter will probably also do this at runtime as it is related to the request itself, not only the route. The same goes for Template where this is too needed. Either way this event listener is required for the system to support all currently available annotations.
